# Utiliser l'image Ubuntu la plus récente comme base
FROM ubuntu:latest

# Mettre à jour la liste des paquets
RUN apt-get update

# Mettre à niveau les logiciels installés
RUN apt-get upgrade -y

# Afficher "Hello, World!" lorsque le conteneur est exécuté
CMD ["echo", "Hello, World!"]
